version: '3.8'
services:
  postgres:
    image: 'postgres:14-alpine'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: next-lms
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'